- name: Run job id {{ id }}
  command: sleep {% if job_duration_ms_min == job_duration_ms_max %}{{ job_duration_ms_max }}{% else %}{{ job_duration_ms_max | random(job_duration_ms_min) / 1000 }}{% endif %}
